// Donations
export const FETCH_DONATIONS_SUCCEED = 'FETCH_DONATIONS_SUCCEED';
export const FETCH_DONATIONS_FAILED = 'FETCH_DONATIONS_FAILED';
export const ADD_DONATION_SUCCEED = 'ADD_DONATION_SUCCEED';